### ISSUE TITLE
Displaying Game Board

### ISSUE THREAD

**Issue by Snaredrumhero** [OU-CS3560/s24-killer-sudoku#1]
Draw the gameboard
* Only on localhost

Need:

- [x] Title "Killer Sudoku" 
- [x] Team Member names
- [x] Timer 
- [x] Button grid for number inputs
   * 
- [ ] Solve button
   * Make button ask if the player is sure before solving
   * Swap the button's text from "solve" to "are you sure?" and if they click again, just solve the puzzle

**Comment by ZacharyWolfe** [comment]
Moved to new issue, and adding 'Are you sure' to features list at the end.
