### ISSUE TITLE
Solver (& Fixing an incorrect board)

### ISSUE THREAD

**Issue by Snaredrumhero** [OU-CS3560/s24-killer-sudoku#3]
Current board state or blank sudoku?
* Start solving from the current board state
* If the current board is unsolvable, then we go from scratch

Method?
* Use a brute force recursive algorithm, with an additional check to be sure that the numbers add up correctly

**Comment by ZacharyWolfe** [comment]
Reveal the hidden data?

**Comment by nickadkins47** [comment]
As of me writing this, the board can be successfuly solved via this solver algorithm, assuming that the board hasnt yet been modified. All i need left to do is implement a way to determine if the board is partially incorrect & fix those mistakes. (maybe also highlight mistakes once "solve" is pressed)

**Comment by nickadkins47** [comment]
Ok this is now fixed in PR #58  , but there are other issues i'll create new posts about.
