### ISSUE TITLE
Pause button bugs

### ISSUE THREAD

**Issue by nickadkins47** [OU-CS3560/s24-killer-sudoku#59]
Put a few ongoing issues w/ pause button below (that i've noticed so far)

-----

- [x] Unpause -> New Game -> Broken Pause Button

if you unpause, then hit new game, the pause button will show up as unpaused & not work (button is unresponsive).
EDIT: Also should add that it still wouldn't work after hitting new game again etc. Only fix is to refresh the page itself.

![firefox_IpYlLNonVa](https://github.com/OU-CS3560/s24-killer-sudoku/assets/122920989/70e5f144-76b7-4372-b5b2-712058d04cba)

-----

- [x] You put stuff into tiles when timer hasnt started yet

(Or just make it so that it automatically starts when you input a number)

![firefox_ogjDWWaIpj](https://github.com/OU-CS3560/s24-killer-sudoku/assets/122920989/09853d7c-d8bd-4ebc-9776-11d3509b8aa3)

**Comment by ZacharyWolfe** [comment]
These issues were all fixed in my branch, just needed to merge.
