### ISSUE TITLE
Killer Grouping - Percent Chances / Generation Enhancements

### ISSUE THREAD

**Issue by Snaredrumhero** [OU-CS3560/s24-killer-sudoku#6]
Current plan: 
Create an array of groupings

**Comment by Snaredrumhero** [comment]
The size of groupings stay pretty consistent. Difficulty is determined largely by the amount of squares hidden when the puzzle starts. 
A good way to group squares together would be by to use a Binomial Distribution type of probability system, where we calculate the probability of connecting to another square based on how likely it would be to get a certain number of n sized groups. After that, just run a recursive function that groups squares together. 
This would make it very easy to tweak the distribution of groupings

https://byjus.com/maths/binomial-distribution/

**Comment by nickadkins47** [comment]
In the future i plan on somewhat reworking the Killer Generation algorithm to be more in line with whats posted here, allowing for more flexibility in how the groups are being generated and such

**Comment by nickadkins47** [comment]
Have yet to put up the PR for it, but this is basically done
