### ISSUE TITLE
Big number Buttons fill every unlocked tile with that number

### ISSUE THREAD

**Issue by nickadkins47** [OU-CS3560/s24-killer-sudoku#60]
Of which i noticed it is specifically unlocked tiles, as opposed to blank tiles, or modified ones etc.

![firefox_fOL0UZOoF2](https://github.com/OU-CS3560/s24-killer-sudoku/assets/122920989/00b20bb8-a420-4958-a4a4-96ac6c5f2678)

**Comment by ZacharyWolfe** [comment]
This was a known bug that was fixed a long time ago, been waiting to merge because I needed to fix the panel more.
