### ISSUE TITLE
Incorrectly Place Tile -> Solve Button -> Tile highlighting is still red on fixed tiles

### ISSUE THREAD

**Issue by nickadkins47** [OU-CS3560/s24-killer-sudoku#61]
After PR #58 , any incorrect tiles are now corrected upon hitting the solve button. However, the highlighting for those tiles is not updated.

![firefox_qDSIBXXoRX](https://github.com/OU-CS3560/s24-killer-sudoku/assets/122920989/b791e9e8-0ca1-4abf-b80d-d5b046a97156)

**Comment by ZacharyWolfe** [comment]
To comment on what's happening in the middle, it appears that there is a space in the (4, 3) cell, so when it's comparing it's actually bringing up false. I can't reproduce the (4, 3) cell 'space' issue but I will put out a fix for the highlighting. Good catch!

**Comment by ZacharyWolfe** [comment]
Will ensure a fix when https://github.com/OU-CS3560/s24-killer-sudoku/issues/62 is closed.

**Comment by ZacharyWolfe** [comment]
Solved with #65
