### ISSUE TITLE
New Game -> Pause broken / already ticking

### ISSUE THREAD

**Issue by nickadkins47** [OU-CS3560/s24-killer-sudoku#66]
after solving & hitting new game, pause button still shows as paused, but the timer is ticking & the button is unresponsive.

EDIT: ok its just generally whenever you hit new game, not explicitly after solving

![firefox_ENCy9ff7d0](https://github.com/OU-CS3560/s24-killer-sudoku/assets/122920989/aeacecca-4009-4fde-b47c-62e2294c408c)

**Comment by ZacharyWolfe** [comment]
Just needed to set the icon, good catch! Solve with #67

**Comment by nickadkins47** [comment]
issue is back in main, but its probably a simple fix; wont be up for that long

**Comment by nickadkins47** [comment]
ok yup its fixed again
